#ifndef __PARALLEL_JAW_CONSTRAINS_HPP_
#define __PARALLEL_JAW_CONSTRAINS_HPP_


#define PARALLEL_JAW_MIN_DIST 0.004 //.002
#define PARALLEL_JAW_MAX_DIST 0.1


#define PARALLEL_JAW_FINGER_WIDTH 1


#define PARALLEL_JAW_NORMAL_THRESHOLD 1


#endif // __PARALLEL_JAW_CONSTRAINS_HPP_
